import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#08111f" },
  center: { justifyContent: "center", alignItems: "center" },
  header: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { color: "#e2e8f0", fontSize: 24, fontWeight: "800" },
  subtitle: { color: "#94a3b8", fontSize: 12, marginTop: 4 },
  navBar: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
    flexWrap: "wrap",
  },
  toolbar: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
  },
  listContent: { padding: 16, gap: 12 },
  formContent: { padding: 16, gap: 10 },
  card: {
    backgroundColor: "#0f172a",
    borderColor: "#1e293b",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  cardTitle: {
    color: "#e2e8f0",
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 6,
  },
  cardMeta: { color: "#94a3b8", fontSize: 12, marginBottom: 4 },
  cardBody: { color: "#cbd5e1", fontSize: 14, lineHeight: 20 },
  input: {
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "#334155",
    color: "#f8fafc",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
  },
  textArea: { minHeight: 110, textAlignVertical: "top" },
  primaryButton: {
    backgroundColor: "#2563eb",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 6,
  },
  primaryButtonText: { color: "white", fontWeight: "700" },
  secondaryButton: {
    backgroundColor: "#172554",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  secondaryButtonText: { color: "#dbeafe", fontWeight: "600" },
  dangerButton: {
    backgroundColor: "#7f1d1d",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  dangerButtonText: { color: "#fee2e2", fontWeight: "700" },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#334155",
    backgroundColor: "#0f172a",
  },
  pillActive: { backgroundColor: "#1d4ed8", borderColor: "#60a5fa" },
  pillText: { color: "#cbd5e1", fontSize: 12 },
  pillTextActive: { color: "#eff6ff", fontWeight: "700" },
  choiceWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  rowGap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  previewImage: {
    width: "100%",
    height: 220,
    borderRadius: 18,
    resizeMode: "cover",
    marginTop: 8,
  },
  audioBox: {
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "#334155",
    borderRadius: 16,
    padding: 12,
    marginTop: 8,
  },
  audioText: { color: "#e2e8f0", marginBottom: 10 },
  detailLine: { color: "#cbd5e1", lineHeight: 22, marginTop: 4 },
  label: { fontWeight: "700", color: "#f8fafc" },
  emptyText: { color: "#94a3b8", paddingHorizontal: 16, paddingVertical: 12 },
  map: { width: "100%", height: 240, borderRadius: 18, marginTop: 12 },
  avatar: { width: 120, height: 120, borderRadius: 60, alignSelf: "center" },
  avatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1e293b",
    borderWidth: 1,
    borderColor: "#334155",
  },
  avatarPlaceholderText: { color: "#cbd5e1", fontWeight: "700" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.65)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#08111f",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1e293b",
  },
});
